version: '3.8'

services:
  model-server:
    image: tensorflow/serving
    command:
      - --model_name=vit
      - --model_base_path=/models/vit_serving/
      - --rest_api_port=8501
    ports:
      - 8501:8501
    tty: true
    volumes:
      - ./tfserving/:/models/
  gradio-app:
    build:
      context: ./gradioapp
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - 7861:7861
    volumes:
      - ./flagged:/app/flagged
  covid-dashboard:
    build:
      context: ./coviddashboard
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - 7862:80
