name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: zero-shot-prediction-dashboard  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of repository
        uses: actions/checkout@v3

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false

#      - name: Build and push container image to registry
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#          file: ./Dockerfile

#  deploy:
#    permissions:
#      contents: none
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Development'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
