name: TfServing Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NEW_IMAGE_TAG: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_857d832c1cff47e281cacd492e5ec597 }}/zspd-tfserving:${{ github.sha }}

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v4
      with:
          python-version: 3.8 #install the python needed

    - name: Install dependencies
      run: |
        pip install -r tfserving/requirements.txt

    - name: Run setup
      run: |  
        python tfserving/setup.py

    - name: Run docker serving image as a daemon
      run: |
        docker run -d --name serving_base tensorflow/serving
        
    - name: Copy the SavedModel to the running TensorFlow Serving container
      run: |
        docker cp ${GITHUB_WORKSPACE}/vit serving_base:/models/vit
        
    - name: Commit changes to base images # we set the MODEL_NAME environment variable to let TensorFlow Serving know which model to expose as services
      run: |
        docker commit --change "ENV MODEL_NAME vit" serving_base $NEW_IMAGE_TAG
        
    - name: Stop serving_base # we do not need serving_base anymore
      run: | 
        docker kill serving_base
        
    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_857d832c1cff47e281cacd492e5ec597 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a34ed7c2c21647749f997e3f9e51ab4a }}
     
    - name: Push image to docker hub
      run: |
        docker push $NEW_IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'zhpd-tfserving'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_TfServing }}
        images: '${NEW_IMAGE_TAG}'
